environment: "dev"

ftp-server:
  host: 'bh8942.banahosting.com'
  port: 21
  folder_remoto_atenciones: 'accenture/atenciones'
  folder_remoto_tickets: 'accenture/tickets'

local-folders:
  carpeta_atenciones: 'data/raw/atenciones'
  carpeta_tickets: 'data/raw/tickets'
  carpeta_detalles: 'data/raw/detalles'

drive-file:
  file_id: '1kmATFQnnHygjzr_pOQ-uj12G2vd45M9cz2-05NgMQ6A'
  file_url: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQHio4-p3RASD9bcoDoUo3GBK98wPyqS3bXnLUq2-FoAaHD2zUgNwbnxUWc5GJuWI8LpIkJb-E6P590/pub?output=xlsx'
  file_name: 'Agencias.xlsx'

files:
  lima_file_name: "Lima.csv"
  provincia_file_name: "Provincia.txt"
  agencias_file_name: "Agencias.xlsx"

sql_server:
  driver: "ODBC Driver 17 for SQL Server"
  server: "DESKTOP-8U804TB"
  database: "Accenture"